AI2projektraporty/AI2projektraporty/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using AI2projektraporty.Data;
using AI2projektraporty.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Authorization;

namespace AI2projektraporty.Controllers
{
    [Authorize]
    [Produces("application/json")]
    [EnableCors("AI2Cors")]
    [Route("api/Reports")]
    public class ReportsController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly AI2Context _context;

        public ReportsController(AI2Context context, UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        // GET: api/Reports

        [HttpGet]
        public async Task<IActionResult> GetReports()
        {
           
            var report = _context.Reports.Where(m => m.UserId == _userManager.GetUserId(User));

            if (report == null)
            {
                return NotFound(report);
            }

            return Ok(report);
        }



        [Route("/Reports")]
        public IActionResult Index()
        {
            return View();
        }

        [Route("/Reports/Pdf/{id}")]
        public IActionResult Pdf([FromRoute] int id)
        {
            var transactions = GetTransactionsForReport(id);
            string date = "";
            double transactionsSum = 0;
            Report report = _context.Reports.SingleOrDefault(m => m.Id == id);
            ICollection<string> titles = new List<string>();
            ICollection<double> amounts = new List<double>();


            foreach (var t in transactions)
            { 
                titles.Add(t.Title);
                amounts.Add(t.Amount);
                transactionsSum += t.Amount;
            }


            if (transactions.Count != 0)
                switch (report.Type)
            {
                
                case Models.Type.Yearly :
                    {
                        date = transactions.First().Date.Year.ToString();
                        break;
                    }
                case Models.Type.Monthly:
                    {
                        date = transactions.First().Date.Month.ToString() + "." + transactions.First().Date.Year.ToString();
                        break;
                    }
                case Models.Type.Daily:
                    {
                        date = transactions.First().Date.Day.ToString() + "." +  transactions.First().Date.Month.ToString() + "." + transactions.First().Date.Year.ToString();
                        break;
                    }
            }
            

            var model = new PdfViewModel
            {
                Report = report,
                Transactions = transactions,
                Titles = titles,
                Amounts = amounts,
                Date = date,
                Sum = transactionsSum
            };

            return View(model);
        }

        [Route("/api/Reports/Pdf/{id}")]
        [HttpGet("{id}")]
        public async Task<IActionResult> DataToPdf([FromRoute] int id)
        {
            var transactions = GetTransactionsForReport(id);
         
            return Ok(transactions);
        }


        // GET: api/Reports/5
        [HttpGet("{id}")]
        public async Task<IActionResult> GetReport([FromRoute] int id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var report = await _context.Reports.SingleOrDefaultAsync(m => m.Id == id && m.UserId == _userManager.GetUserId(User));

            if (report == null)
            {
                return NotFound();
            }

            return Ok(report);
        }

        public ICollection<Transaction> GetTransactionsForReport(int id)
        {
            if (!ModelState.IsValid)
            {
                return null;
            }

            var report = _context.Reports.SingleOrDefault(m => m.Id == id && m.UserId == _userManager.GetUserId(User));
            var reporttransactions = _context.ReportTransaction.Where(m => m.ReportId == id).ToList();
            ICollection<Transaction> transactions = new List<Transaction>();
            foreach (var transaction in reporttransactions)
            {
                transactions.Add( _context.Transactions.SingleOrDefault(m => m.Id == transaction.TransactionId));
            }

            return transactions;
        }



        // POST: api/Reports
        [HttpPost]
        public async Task<IActionResult> PostReport([FromBody] Report report)
        {
            var date = DateTime.Now;
            var year = date.Year;
            var month = date.Month;
            var day = date.Day;
            
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            report.UserId = _userManager.GetUserId(User);

            _context.Reports.Add(report);
            _context.SaveChanges();
            List<Transaction> transactions = new List<Transaction>();

           switch (report.Type)
            {
                case Models.Type.Daily:
                    // transactions = _context.Transactions.Where(m => m.Date <= DateTime.Now && m.Date >= (new DateTime(year - 1, month, day))).ToList();
                    transactions = _context.Transactions.Where(m => m.Date.Day == DateTime.Now.Day).ToList();
                    break;
                case Models.Type.Monthly:
                    transactions = _context.Transactions.Where(m => m.Date.Month == DateTime.Now.Month).ToList();
                    break;
                case Models.Type.Yearly:
                    transactions = _context.Transactions.Where(m => m.Date.Year == DateTime.Now.Year).ToList();
                    break;
            }
            

            foreach (var transaction in transactions)
            {
                if (_context.Transactions.Find(transaction.Id) != null)
                {
                    _context.ReportTransaction.Add(new ReportTransaction { ReportId = report.Id, TransactionId = transaction.Id });
                }
            }

            await _context.SaveChangesAsync();

            return CreatedAtAction("GetReport", new { id = report.Id }, report);
        }

        // DELETE: api/Reports/5
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteReport([FromRoute] int id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var report = await _context.Reports.SingleOrDefaultAsync(m => m.Id == id);
            if (report == null)
            {
                return NotFound();
            }

            _context.Reports.Remove(report);
            await _context.SaveChangesAsync();

            return Ok(report);
        }

        private bool ReportExists(int id)
        {
            return _context.Reports.Any(e => e.Id == id);
        }

        [Route("addTransactions/{id}")]
        [HttpPut("{id}")]
        public async Task<IActionResult> AddTransactionsToReport([FromRoute] int id, [FromBody] List<Transaction> transactions)
        {
            Report report = _context.Reports.SingleOrDefault(m => m.Id == id);
            if(report.ReportTransaction == null)
            {
                report.ReportTransaction = new List<ReportTransaction>();
            }
            
            foreach (var transaction in transactions)
            {
                if (_context.Transactions.Find(transaction.Id) != null)
                {
                    report.ReportTransaction.Add(new ReportTransaction { Report = report, TransactionId = transaction.Id });
                }
                else
                {
                    return NotFound();
                }
            }
            
           


            
            _context.SaveChanges();
            return Ok();
        }
    }
}

AI2projektraporty/AI2projektraporty/Controllers/TransactionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using AI2projektraporty.Data;
using AI2projektraporty.Models;
using Microsoft.AspNetCore.Cors;

namespace AI2projektraporty.Controllers
{
    [Produces("application/json")]
    [EnableCors("AI2Cors")]
    [Route("api/Transactions")]
    public class TransactionsController : Controller
    {
        private readonly AI2Context _context;

        public TransactionsController(AI2Context context)
        {
            _context = context;
        }

        // GET: api/Transactions
        [HttpGet]
        public IEnumerable<Transaction> GetTransactions()
        {
            return _context.Transactions;
        }
        
        [Route("/Transactions")]
        public IActionResult Index()
        {
            return View();
        }

        // GET: api/Transactions/5
        [HttpGet("{id}")]
        public async Task<IActionResult> GetTransaction([FromRoute] int id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var transaction = await _context.Transactions.SingleOrDefaultAsync(m => m.Id == id);

            if (transaction == null)
            {
                return NotFound();
            }

            return Ok(transaction);
        }

        [Route("date/{year}")]
        [HttpGet("{year}")]
        public async Task<IActionResult> GetTransactionByYear([FromRoute] int year)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var transaction = _context.Transactions.Where(m => m.Date.Year == year);


            if (transaction == null)
            {
                return NotFound();
            }

            return Ok(transaction);
        }

        [Route("date/{year}/{month}")]
        [HttpGet("{year}, {month}")]
        public async Task<IActionResult> GetTransactionByMonth([FromRoute] int year, [FromRoute] int month)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var transaction = _context.Transactions.Where(m => m.Date.Year == year && m.Date.Month == month);


            if (transaction == null)
            {
                return NotFound();
            }

            return Ok(transaction);
        }

        [Route("date/{year}/{month}/{day}")]
        [HttpGet("{year}, {month}, {day}")]
        public async Task<IActionResult> GetTransactionByDay([FromRoute] int year, [FromRoute] int month, [FromRoute] int day)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            
            var transaction = _context.Transactions.Where(m => m.Date.Year == year && m.Date.Month == month && m.Date.Day == day);


            if (transaction == null)
            {
                return NotFound();
            }

            return Ok(transaction);
        }

        // PUT: api/Transactions/5
        [HttpPut("{id}")]
        public async Task<IActionResult> PutTransaction([FromRoute] int id, [FromBody] Transaction transaction)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != transaction.Id)
            {
                return BadRequest();
            }

            _context.Entry(transaction).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!TransactionExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/Transactions
        [HttpPost]
        public async Task<IActionResult> PostTransaction([FromBody] Transaction transaction)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            transaction.Date = DateTime.Now;

            _context.Transactions.Add(transaction);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetTransaction", new { id = transaction.Id }, transaction);
        }

        // DELETE: api/Transactions/5
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteTransaction([FromRoute] int id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var transaction = await _context.Transactions.SingleOrDefaultAsync(m => m.Id == id);
            if (transaction == null)
            {
                return NotFound();
            }

            _context.Transactions.Remove(transaction);
            await _context.SaveChangesAsync();

            return Ok(transaction);
        }

        private bool TransactionExists(int id)
        {
            return _context.Transactions.Any(e => e.Id == id);
        }
    }
}

AI2projektraporty/AI2projektraporty/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BRG&M</title>
    <link rel="icon" href="~/icon.ico" sizes="16x16" type="image/png">

    <environment include="Development">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="~/lib/css/fontawesome.min.css">
        <script defer src="~/lib/js/all.js"></script>
        <!-- Bootstrap core CSS -->
        <link href="~/lib/css/bootstrap.min.css" rel="stylesheet">
        <!-- Material Design Bootstrap -->
        <link href="~/lib/css/mdb.min.css" rel="stylesheet">
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/lib/css/fontawesome.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/lib/css/mdb.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    </environment>
  
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark blue fixed-top" style="font-size: 1.2em">
        <a class="navbar-brand font-weight-bold" asp-controller="Home" asp-action="Index" style="font-size: 1.3em">
            <span class="d-none d-md-block">Business reports generator & manager</span>
            <span class="d-block d-md-none">BRG&M</span>
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse text-center" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                @if (SignInManager.IsSignedIn(User))
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Reports" asp-action="Index"><b><i class="fas fa-file-alt"></i> Reports </b></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Transactions" asp-action="Index"><b><i class="fas fa-money-bill-alt"></i> Transactions </b></a>
                    </li>
                }
            </ul>
            <ul class="navbar-nav">
                @if (!SignInManager.IsSignedIn(User))
                {
                    <button class="btn primary-color-dark" data-toggle="modal" data-target="#myModal"><i class="fas fa-sign-in-alt"></i> Login</button>
                    <button class="btn warning-color-dark" data-toggle="modal" data-target="#myModal2"><i class="fas fa-user-plus"></i> Register</button>
                }
                else
                {
                    <li class="nav-item">
                        <a class="nav-link mt-2" asp-controller="Manage" asp-action="Index" title="Manage"><b>Hello @UserManager.GetUserName(User)!</b></a>
                    </li>
                    <li class="nav-item align-self-center">
                        <form asp-controller="Account" asp-action="Logout" method="post">
                            <button title="Logout" type="submit" class="btn primary-color-dark"><i class="fas fa-power-off" aria-hidden="true"></i></button>
                        </form>
                    </li>
                }
            </ul>
        </div>
    </nav>
    @await Html.PartialAsync("_LoginPartial")
    @RenderBody()
    <footer id="footer" class="page-footer align-content-center blue pt-2">
        <div class="container-fluid pt-2">
            <div class="row">
                <div class="col-md-6 pt-2">
                    <h3 class="title">Business reports generator & manager</h3>
                    <p>ASP.NET Core MVC web application</p>
                    <h5 class="title">Technologies</h5>
                    <ul class="list-inline">
                        <li><a href="https://docs.microsoft.com/pl-pl/aspnet/core/">ASP.NET Core 2.0</a></li>
                        <li><a href="https://jquery.com/">jQuery</a></li>
                        <li><a href="https://getbootstrap.com/">Bootstrap</a> & <a href="http://mdbootstrap.com">MDBootstrap</a></li>
                    </ul>
                </div>
                <div class="col-md-6 pt-2">
                    <h3 class="title">Authors</h3>
                    <ul>
                        <li>Michał Rembisz</li>
                        <li>Jaromir Sarzyński</li>
                        <li>Daniel Smolak</li>
                        <li>Krystian Pinderski</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="text-center">
                © 2018 Copyright: <a asp-controller="Home" asp-action="Index"> Business reports generator & manager</a>
            </div>
        </div>
    </footer>

    <environment include="Development">
        <script type="text/javascript" src="~/lib/js/jquery-3.2.1.min.js"></script>
        <script type="text/javascript" src="~/lib/js/popper.min.js"></script>
        <script type="text/javascript" src="~/lib/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="~/lib/js/mdb.min.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/popper.min.js">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous">
        </script>
        <script defer src="~/lib/js/all.js" asp-append-version="true"></script>
        <script src="~/lib/js/mdb.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>